### ISSUE TITLE
Plot error: plot_size must be a list of two positive integers.

### ISSUE THREAD

**Issue by Rillke** [ilifau/assStackQuestion#35]
When running the health check in `Administration -> Plugins -> assStackQuestion` we receive:
`Plot error: plot_size must be a list of two positive integers.` on two of the plots. I would expect that the test completes, and 3 graphs are shown.

----
We have installed the following products:
* ILIAS 5.3.x
* STACK Maxima Server
    * https://hub.docker.com/r/unihalle/maximapool/
    * sbcl
    * Maxima version 5.41.0
    * STACK version 2017121800
* assStackQuestion Plugin version: 12439ff1a3a16280e115ce1fab4a23b985c90509

----

I noticed that when adding a plot size specification, e.g.`,[size,250,250]`, I receive the expected result. Is there an option I forgot to tick? A default plot size that must be specified?

INPUT:
```
"input=cab:block([+RANDOM_SEEDcaschat2],+stack_randseed(0),+make_multsgn(\"dot\"),+make_complexJ(\"i\"),+make_arccos(\"cos-1\"),+OPT_NoFloats:true,+sqrtdispflag:true,+simp:true,+assume_pos:false,+assume_real:false,+lmxchar:\"[\",+print(\"[TimeStamp=+[+0+],+Locals=+[+\")+,+print(\"-1=[+error=+[\"),+cte(\"__stackmaximaversion\",errcatch(__stackmaximaversion:stackmaximaversion))+,+print(\"0=[+error=+[\"),+cte(\"caschat0\",errcatch(caschat0:plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3])))+,+print(\"1=[+error=+[\"),+cte(\"caschat1\",errcatch(caschat1:plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3],grid2d)))+,+print(\"2=[+error=+[\"),+cte(\"caschat2\",errcatch(caschat2:plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3],[box,+false],[yx_ratio,+1],[axes,+solid],[xtics,+-3,+1,+3],[ytics,+-3,+1,+3],[size,250,250])))+,+print(\"]+]\")+,+return(true)+);+
+&timeout=5000&ploturlbase=!ploturl!&version=2017121800"


Plots:
errors out: [x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3]
errors out: [sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3],grid2d
works: [sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3],[box,+false],[yx_ratio,+1],[axes,+solid],[xtics,+-3,+1,+3],[ytics,+-3,+1,+3],[size,250,250]
```

OUTPUT:
```
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
Maxima restarted.
(%i5) 
(%o5) "/opt/maximapool/2017121800/maximalocal.mac"
(%i6) 
[TimeStamp= [ 0 ], Locals= [  
-1=[ error= [ 
], key = [ 
__stackmaximaversion 
] 
, value = [ 
2017121800 
], dispvalue = [ 
2017121800 
], display = [ 
2017121800 
] 
],  
0=[ error= [ 
Plot error: plot_size must be a list of two positive integers.
], key = [ 
caschat0 
] 
, value = [], display = [] 
],  
1=[ error= [ 
Plot error: plot_size must be a list of two positive integers.
], key = [ 
caschat1 
] 
, value = [], display = [] 
],  
2=[ error= [ 
plot2d: some values were clipped.
plot2d: some values were clipped.
], key = [ 
caschat2 
] 
, value = [ 
" <html><div class=\"stack_plot\"><img src='!ploturl!stackplot-3739179625-57136044.png' alt='STACK auto-generated plot of [sin(x),x,x^2,x^3] with parameters [[x,-3,3],[y,-3,3],[box,false],[yx_ratio,1],[axes,solid],[xtics,-3,1,3],[ytics,-3,1,3],[size,250,250]]' width='250' /></div></html> " 
], dispvalue = [ 
" <html><div class=\"stack_plot\"><img src='!ploturl!stackplot-3739179625-57136044.png' alt='STACK auto-generated plot of [sin(x),x,x^2,x^3] with parameters [[x,-3,3],[y,-3,3],[box,false],[yx_ratio,1],[axes,solid],[xtics,-3,1,3],[ytics,-3,1,3],[size,250,250]]' width='250' /></div></html> " 
], display = [ 

 \mbox{ <html><div class="stack\_plot"><img src='!ploturl!stackplot-3739179625-57136044.png' alt='STACK auto-generated plot of [sin(x),x,x^2,x^3] with parameters [[x,-3,3],[y,-3,3],[box,false],[yx\_ratio,1],[axes,solid],[xtics,-3,1,3],[ytics,-3,1,3],[size,250,250]]' width='250' /></div></html> } 
] 
],  
] ] 
(%o9) true
(%o10) 
```

![ilias-5 3](https://user-images.githubusercontent.com/2311611/42038877-4dbe9878-7aec-11e8-8b4b-f337636ae6fc.png)

**Comment by jcopado** [comment]
Hello!

Thanks for using STACK in ILIAS
In order to have only one bugtracker, to report bugs in this plugin we used to workwith the ILIAS bug tracker Mantis (https://www.ilias.de/mantis/). This issue is due to the Maxima Installation your are running, I saw you are using the maxima docker from unihalle, so, you should ask them why this error happens.

Thank you!

**Comment by Rillke** [comment]
> In order to have only one bugtracker, to report bugs in this plugin we used to workwith the ILIAS bug tracker Mantis (https://www.ilias.de/mantis/).

ILIAS Mantis is a _walled garden_. I prefer to avoid them for open source software.

> This issue is due to the Maxima Installation

Missing evidence. Might be due to the missing `size` specifications in the PHP-generated Maxima commands, too.

In https://github.com/ilifau/assStackQuestion/blob/dev53/classes/stack/maxima/stackmaxima.mac#L805 of the STACK version that comes with this plugin, there is a check for `plot_size` specifications that will throw an error, if omitted. So I assume it's a bug in your PHP implementation not sending out the `plot_size`.
