### ISSUE TITLE
ILIAS 7.4 and your branch master-ilias7: Composer-Error

### ISSUE THREAD

**Issue by wolfganghuebsch** [ilifau/assStackQuestion#90]
composer install --no-dev

Leads to:

Warning: Ambiguous class resolution, "stack_cas_castext_castextparser" was found in both "/var/www/html/ilias/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/stack/cas/castext/autogen/castextparser.class.php" and "/var/www/html/ilias/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/stack/cas/castext/castext.peg.inc", the first will be used.
Warning: Ambiguous class resolution, "stack_cas_castext_parsetreenode" was found in both "/var/www/html/ilias/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/stack/cas/castext/autogen/castextparser.class.php" and "/var/www/html/ilias/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/stack/cas/castext/castext.peg.inc", the first will be used.

Reason (from mantis):

classes with ambigous names

**Comment by jcopado** [comment]
Solved in version 3.4.1
